[2/2] Add pipeline commands
mattermost/mattermost-plugin-circleci pull request #16
Opened 2020-10-02 10:52 UTC by darkLord19

- trigger pipeline by project slug
- trigger pipeline for specific branch of project

2020-10-02 21:43 UTC, nathanaelhoun requested changes
Tested and works! Just an important change: warn the user when the pipeline is not triggered

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
> +	p.API.LogError("uparmar no error")
This should be a `p.API.LogDebug()` I think

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
> +		p.API.LogError("uparmar", err.Error())
What does "uparmar" means?

Also, `err.Error()` should have a key with it:
```suggestion
		p.API.LogError("uparmar", "err", err.Error())
```

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
> +	trigger.AddTextArgument("<branch>", pipelineTriggerHint, "")
```suggestion
	trigger.AddTextArgument("<branch>", "The branch to trigger the pipeline on", "")
```

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
>  	trigger.AddTextArgument("< vcs-slug/org-name/repo-name >", pipelineTriggerHint, "")
```suggestion
	trigger.AddTextArgument("< vcs-slug/org-name/repo-name >", "The repo to trigger the pipeline on. Ex: gh/mattermost/mattermost-server", "")
```

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
>  			"Could not trigger pipeline for project ", projectSlug, err.Error())}
We should also send a message to the user, or nothing will happen from his side

2020-10-02 21:43 UTC, nathanaelhoun commented on server/plugin/pipeline.go
> +				Pretext:  "Triggered pipeline for project " + projectSlug + "branch " + branch,
```suggestion
				Fallback: fmt.Sprintf("Pipeline triggered successfully for project %s for branch: %s", projectSlug, branch),
				Pretext:  fmt.Sprintf("Triggered pipeline for project `%s` branch `%s`", projectSlug, branch),
```

2020-10-03 06:44 UTC, darkLord19 commented on server/plugin/pipeline.go
> +		p.API.LogError("uparmar", err.Error())
ohh i added it for debugging purposes and uparmar is to make my logs stand out from other logs! will remove it.

2020-10-03 07:06 UTC, nathanaelhoun approved these changes
A little nit pick for the error message, otherwise LGTM!

2020-10-03 07:06 UTC, nathanaelhoun commented on server/plugin/pipeline.go
> +	}
Branch `master` should be before the warning message to avoid empty branch-name in warning message.
```suggestion
	if branch == "" {
		branch = "master"
	}
	if err != nil {
		return p.sendEphemeralResponse(args, fmt.Sprintf("Could not trigger pipeline for project %s on `%s` branch", projectSlug, branch)),
			&model.AppError{Message: fmt.Sprintf("%s%s. err %s",
				"Could not trigger pipeline for project ", projectSlug, err.Error())}
	}

```

2020-10-03 07:25 UTC, merged